# Generated by Django 3.1.7 on 2021-03-28 20:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='images/', verbose_name='Фото для превью страницы О нас')),
                ('second_preview_image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='images/', verbose_name='Фото для превью страницы О нас 2')),
                ('our_mission', models.CharField(max_length=200, verbose_name='Наша миссия')),
                ('our_vision', models.CharField(max_length=200, verbose_name='Наше видиние')),
                ('our_value', models.CharField(max_length=200, verbose_name='Наща ценность')),
                ('professional_employees', models.IntegerField(verbose_name='Количество профессиональных юристов')),
                ('succses_areas', models.IntegerField(verbose_name='Количество успешных дел')),
                ('clients_work', models.IntegerField(verbose_name='Клиентов в работе')),
                ('consultation_price', models.IntegerField(default=0, verbose_name='Цена консультации')),
            ],
            options={
                'verbose_name': 'Информация страницы О нас',
                'verbose_name_plural': 'Информация страницы О нас',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Контактный телефон')),
                ('sender', models.EmailField(max_length=254, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=20, verbose_name='Отчество')),
                ('specialization', models.CharField(max_length=40, verbose_name='Специализация')),
                ('about', models.CharField(max_length=300, verbose_name='О сотруднике')),
                ('employee_image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='employees_images/', verbose_name='Фото')),
                ('vk_url', models.URLField(blank=True, verbose_name='ссылка на вк')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='ссылка на whatsapp')),
                ('telegram_url', models.URLField(blank=True, verbose_name='ссылка на telegram')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='PartnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=20, verbose_name='Название компании')),
                ('partner_url', models.URLField(verbose_name='ссылка на сайт компании')),
                ('partner_logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='partner_logo/', verbose_name='Лого компании')),
            ],
            options={
                'verbose_name': 'Компания-клиент',
                'verbose_name_plural': 'Компании-клиенты',
            },
        ),
        migrations.CreateModel(
            name='Practice_areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('preview_text', models.CharField(max_length=400, verbose_name='Текст описания')),
                ('overview_text', models.TextField(verbose_name='Полный текст описания')),
                ('preview_image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='practice_image/preview/', verbose_name='Превью услуги')),
                ('overview_image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='practice_image/', verbose_name='Фото для детального описания')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='Текст вопроса')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('validation', models.CharField(blank=True, choices=[('y', 'Да'), ('n', 'Нет')], default='n', max_length=1)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='images/', verbose_name='Логотип сайта')),
                ('favicon', easy_thumbnails.fields.ThumbnailerImageField(upload_to='images/', verbose_name='Логотип сайта во вкладке')),
                ('name', models.CharField(max_length=20, verbose_name='Название компании')),
                ('vk_url', models.URLField(verbose_name='Ссылка на вк')),
                ('whatsapp_url', models.URLField(verbose_name='Ссылка на whatsapp')),
                ('telegram_url', models.URLField(verbose_name='Ссылка на telegram')),
                ('instagram_url', models.URLField(verbose_name='Ссылка на instagram')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта сайта')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='89120157067', max_length=128, region=None, verbose_name='Контактный телефон')),
            ],
            options={
                'verbose_name': 'Контент сайта',
                'verbose_name_plural': 'Контент сайта',
            },
        ),
        migrations.CreateModel(
            name='SertificatesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sertificat_image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='images/', verbose_name='Сертификат')),
                ('id_about_page_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.aboutpagemodel')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200, verbose_name='Текст ответа')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата ответа')),
                ('validation', models.CharField(choices=[('y', 'Да'), ('n', 'Нет')], default='n', max_length=1, verbose_name='Валидация')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.questions')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
