# Generated by Django 3.1.7 on 2021-05-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_auto_20210530_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название компании'),
        ),
    ]
