# Generated by Django 3.1.7 on 2021-05-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_auto_20210530_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeModel',
        ),
        migrations.DeleteModel(
            name='PartnerModel',
        ),
    ]
