# Generated by Django 3.1.7 on 2021-05-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_auto_20210530_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на instagram'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на telegram'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='vk_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на вк'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на whatsapp'),
        ),
    ]
