# Generated by Django 3.1.7 on 2021-05-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_auto_20210531_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice_areas',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название услуги'),
        ),
    ]
